TekoTestApp/Models/ApplicationDbContext.cs
using System.Data.Entity;

namespace TekoTestApp.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext() : base("DefaultConnection")
        {
        }

        public DbSet<Employee> Employees { get; set; }
        public DbSet<Vacation> Vacations { get; set; }
    }
}

TekoTestApp/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TekoTestApp.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public int Age { get; set; }
    }
}

TekoTestApp/Models/EmployeeVacationData.cs
using System.Collections.Generic;
using TekoTestApp.Models;

public class EmployeeVacationData
{
    public List<Employee> Employees { get; set; }
    public List<Vacation> Vacations { get; set; }
}

TekoTestApp/Models/Vacation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TekoTestApp.Models
{
    public class Vacation
    {
        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public Employee Employee { get; set; }
    }
}

TekoTestApp/ViewModels/EmployeeDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TekoTestApp.Models;

namespace TekoTestApp.ViewModels
{
    public class EmployeeDetailsViewModel
    {
        public Employee Employee { get; set; }
        public List<Vacation> Vacations { get; set; }
        public Vacation NewVacation { get; set; }
        public EmployeeVacationData IntersectionFromMyDepYounger30 { get; set; }
        public EmployeeVacationData Between30and50FemaleNotMyDep {  get; set; }
        public EmployeeVacationData Older50AnyDep { get; set; }
        public EmployeeVacationData NotIntersection {  get; set; }


    }
}

TekoTestApp/ViewModels/VacationViewModel.cs
using System.Collections.Generic;
using TekoTestApp.Models;

namespace TekoTestApp.ViewModels
{
    public class VacationViewModel
    {
        public List<Vacation> Vacations { get; set; }
        public Vacation NewVacation { get; set; }
    }
}

TekoTestApp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TekoTestApp.Models;  
using TekoTestApp.Services;
using TekoTestApp.ViewModels;

namespace TekoTestApp.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext(); 



        public ActionResult Index()
        {
            var employees = db.Employees.ToList(); 
            return View(employees); 
        }

        public ActionResult Details(int id)
        {
            EmployeeVacationService employeeVacationService = new EmployeeVacationService(db);
            var employee = db.Employees.Find(id);

            if (employee == null)
            {
                return HttpNotFound();
            }


            var vacations = db.Vacations.Where(v => v.Employee.Id == id).ToList();

            var younger30MyDep = employeeVacationService.GetEmployeeVacationDataYounger30MyDep(id);
            var between30and50FemaleNotMyDep = employeeVacationService.GetEmployeeVacationDataBetween30and50FemaleNotMyDep(id);
            var older50AnyDep = employeeVacationService.GetEmployeeVacationDataOlder50AnyDep(id);
            var notIntersect = employeeVacationService.GetEmployeeVacationDataNoIntersection(id);

            var viewModel = new EmployeeDetailsViewModel
            {
                Employee = employee,
                Vacations = vacations,
                IntersectionFromMyDepYounger30 = younger30MyDep,
                Older50AnyDep = older50AnyDep,
                NotIntersection = notIntersect,
                Between30and50FemaleNotMyDep = between30and50FemaleNotMyDep
            };

            viewModel.NewVacation = new Vacation
            {
                Employee = employee
            };

            return View(viewModel);
        }




    }
}

TekoTestApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TekoTestApp.Models;
using TekoTestApp.Services;

namespace TekoTestApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GenerateData()
        {
            DataGeneratorService dataGeneratorService = new DataGeneratorService();

            List<Employee> employees = dataGeneratorService.GenerateRandomEmployees(100);

            List<Vacation> vacations = dataGeneratorService.GenerateRandomVacations(employees);

            using (var context = new ApplicationDbContext())
            {
                context.Employees.AddRange(employees);
                context.Vacations.AddRange(vacations);

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        public ActionResult ViewEmployees()
        {
            return View();
        }

        public ActionResult ViewVacations()
        {
            return View();
        }
    }

}

TekoTestApp/Controllers/VacationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TekoTestApp.Models;
using TekoTestApp.ViewModels;

namespace TekoTestApp.Controllers
{
    public class VacationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var viewModel = new VacationViewModel
            {
                Vacations = db.Vacations.Include("Employee").ToList(),
                NewVacation = new Vacation() // Инициализируем объект для формы
            };
            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Create(VacationViewModel vacation)
        {
            if (ModelState.IsValid)
            {
                // Проверьте длину отпуска
                TimeSpan vacationLength = vacation.NewVacation.EndDate - vacation.NewVacation.StartDate;
                var employee = db.Employees.Find(vacation.NewVacation.Employee.Id);
                if (vacationLength.TotalDays <= 14)
                {

                    if (employee == null)
                    {
                        return HttpNotFound();
                    }

                    var newVacation = new Vacation
                    {
                        StartDate = vacation.NewVacation.StartDate,
                        EndDate = vacation.NewVacation.EndDate,
                        Employee = employee 
                    };

                    db.Vacations.Add(newVacation);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Employee", new { id = employee.Id });
                }
                else
                {
                    return RedirectToAction("Details", "Employee", new { id = employee.Id });
                }
            }

            return View(vacation);
        }

        [HttpPost]
        public ActionResult DeleteVacation(int employeeId, int vacationId)
        {
            var vacation = db.Vacations.Find(vacationId);

            if (vacation == null)
            {
                return HttpNotFound();
            }

            db.Vacations.Remove(vacation);
            db.SaveChanges();

            return RedirectToAction("Details", "Employee", new { id = employeeId });
        }



    }
}

TekoTestApp/Views/Employee/Details.cshtml
@model TekoTestApp.ViewModels.EmployeeDetailsViewModel

<h2>Информация о сотруднике</h2>

<table class="table">
    <tr>
        <th>Имя</th>
        <td>@Model.Employee.FullName</td>
    </tr>
    <tr>
        <th>Должность</th>
        <td>@Model.Employee.Position</td>
    </tr>
    <tr>
        <th>Возраст</th>
        <td>@Model.Employee.Age</td>
    </tr>
</table>

<div style="margin-bottom: 40px;"></div>

<h2>Добавить новый отпуск</h2>

@using (Html.BeginForm("Create", "Vacation", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.HiddenFor(model => model.NewVacation.Employee.Id)
        @Html.HiddenFor(model => model.NewVacation.Employee.FullName)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NewVacation.StartDate)
        @Html.EditorFor(model => model.NewVacation.StartDate, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToShortDateString() } })
        @Html.ValidationMessageFor(model => model.NewVacation.StartDate)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NewVacation.EndDate)
        @Html.EditorFor(model => model.NewVacation.EndDate, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.AddDays(14).ToShortDateString() } })
        @Html.ValidationMessageFor(model => model.NewVacation.EndDate)
    </div>

    <div style="margin-bottom: 20px;"></div>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </div>
}


<div style="margin-bottom: 20px;"></div>
<h2>Отпуски</h2>

<table class="table">
    <thead>
        <tr>
            <th>Дата начала</th>
            <th>Дата окончания</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var vacation in Model.Vacations)
        {
            <tr>
                <td>@vacation.StartDate.ToShortDateString()</td>
                <td>@vacation.EndDate.ToShortDateString()</td>
                <td>
                    @using (Html.BeginForm("DeleteVacation", "Vacation", new { vacationId = vacation.Id }, FormMethod.Post, new { onsubmit = "return confirm('Вы уверены, что хотите удалить этот отпуск?');" }))
                    {
                        @Html.Hidden("employeeId", Model.Employee.Id)
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div style="margin-bottom: 40px;"></div>
<h2>Пересечение отпуска с сотрудниками моего отдела. Сотрудники моложе 30 лет.</h2>

<table class="table">
    <thead>
        <tr>
            <th>Сотрудник</th>
            <th>Возраст</th>
            <th>Должность</th>
            <th>Отпуск</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var intersectingEmployee in Model.IntersectionFromMyDepYounger30.Employees)
        {
            <tr>
                <td>@intersectingEmployee.FullName</td>
                <td>@intersectingEmployee.Age</td>
                <td>@intersectingEmployee.Position</td>
                <td>
                    @foreach (var intersectingVacation in Model.IntersectionFromMyDepYounger30.Vacations.Where(v => v.Employee.Id == intersectingEmployee.Id))
                    {
                        <text>@intersectingVacation.StartDate.ToShortDateString() - @intersectingVacation.EndDate.ToShortDateString()</text>
                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div style="margin-bottom: 40px;"></div>
<h2>Пересечение отпуска с сотрудниками-женщинами не из моего отдела. Возраст сотрудников - старше 30, но моложе 50.</h2>

<table class="table">
    <thead>
        <tr>
            <th>Сотрудник</th>
            <th>Возраст</th>
            <th>Должность</th>
            <th>Отпуск</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var intersectingEmployee in Model.Between30and50FemaleNotMyDep.Employees)
        {
            <tr>
                <td>@intersectingEmployee.FullName</td>
                <td>@intersectingEmployee.Age</td>
                <td>@intersectingEmployee.Position</td>
                <td>
                    @foreach (var intersectingVacation in Model.Between30and50FemaleNotMyDep.Vacations.Where(v => v.Employee.Id == intersectingEmployee.Id))
                    {
                        <text>@intersectingVacation.StartDate.ToShortDateString() - @intersectingVacation.EndDate.ToShortDateString()</text>
                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div style="margin-bottom: 40px;"></div>
<h2>Пересечение отпуска с сотрудниками из любого отдела. Возраст сотрудников - старше 50 лет.</h2>

<table class="table">
    <thead>
        <tr>
            <th>Сотрудник</th>
            <th>Возраст</th>
            <th>Должность</th>
            <th>Отпуск</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var intersectingEmployee in Model.Older50AnyDep.Employees)
        {
            <tr>
                <td>@intersectingEmployee.FullName</td>
                <td>@intersectingEmployee.Age</td>
                <td>@intersectingEmployee.Position</td>
                <td>
                    @foreach (var intersectingVacation in Model.Older50AnyDep.Vacations.Where(v => v.Employee.Id == intersectingEmployee.Id))
                    {
                        <text>@intersectingVacation.StartDate.ToShortDateString() - @intersectingVacation.EndDate.ToShortDateString()</text>
                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div style="margin-bottom: 40px;"></div>
<h2>Отпуска без пересечения.</h2>

<table class="table">
    <thead>
        <tr>
            <th>Сотрудник</th>
            <th>Возраст</th>
            <th>Должность</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var intersectingEmployee in Model.NotIntersection.Employees)
        {
            <tr>
                <td>@intersectingEmployee.FullName</td>
                <td>@intersectingEmployee.Age</td>
                <td>@intersectingEmployee.Position</td>
            </tr>
        }
    </tbody>
</table>

TekoTestApp/Views/Employee/Index.cshtml
@model List<TekoTestApp.Models.Employee>

<h2>Список сотрудников</h2>

<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Должность</th>
            <th>Возраст</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td><a href="@Url.Action("Details", "Employee", new { id = employee.Id })">@employee.FullName</a></td>
                <td>@employee.Position</td>
                <td>@employee.Age</td>
            </tr>
        }
    </tbody>
</table>

TekoTestApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<h2>Добро пожаловать на главную страницу!</h2>

<div>
    <a href="@Url.Action("Index", "Vacation")" class="btn btn-primary">Перейти к отпускам</a>
</div>

<div style="margin-top: 10px;">
    <a href="@Url.Action("Index", "Employee")" class="btn btn-primary">Перейти к работникам</a>
</div>

TekoTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Тестовое приложение</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Тестовое приложение", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Переключить навигацию" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Отпуска", "Index", "Vacation", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Сотрудники", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Тестовое приложение</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TekoTestApp/Views/Vacation/Index.cshtml
@model TekoTestApp.ViewModels.VacationViewModel
<h2>Список отпусков</h2>


<table class="table">
    <thead>
        <tr>
            <th>Имя сотрудника</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var vacation in Model.Vacations)
        {
            <tr>
                <td>@vacation.Employee.FullName</td>
                <td>@vacation.StartDate.ToShortDateString()</td>
                <td>@vacation.EndDate.ToShortDateString()</td>
            </tr>
        }
    </tbody>
</table>